# k nearest neighbour
         
         # k-Nearest Neighbors

K-nearest neighbors (KNN) is a type of supervised learning algorithm which is used for both regression and classification purposes, but mostly it is used for the later. Given a dataset with different classes, KNN tries to predict the correct class of test data by calculating the distance between the test data and all the training points. It then selects the k points which are closest to the test data.  Once the points are selected, the algorithm calculates the probability (in case of classification) of the test point belonging to the classes of the k training points and the class with the highest probability is selected. In the case of a regression problem, the predicted value is the mean of the k selected training points.


Let’s understand this with an illustration:


1)	Given a training dataset as given below. We have a new test data that we need to assign to one of the two classes.

<img src="1.png" width="">
                                      

2)	Now, the k-NN algorithm calculates the distance between the test data and the given training data.

<img src="2.png" width="">

                                                        
3)	After calculating the distance, it will select the k training points which are nearest to the test data. Let’s assume the value of k is 3 for our example.

<img src="3.png" width="">                                            


4)	Now, 3 nearest neighbors are selected, as shown in the figure above. Let’s see in which class our test data will be assigned :

Number of Green class values = 2
Number of Red class values = 1
Probability(Green) = 2/3
Probability(Red) = 1/3

Since the probability for Green class is higher than Red, the k-NN algorithm will assign the test data to the Green class.

Similarly, if this were the case of a regression problem, the predicted value for the test data will simply be the mean of all the 3 nearest values.

This is the basic working algorithm for k-NN. Let’s understand how the distance is calculated :

### Euclidean Distance:

It is the most commonly used method to calculate the distance between two points.
The Euclidean distance between two points ‘p(p1,p2)’ and ‘q(q1,q2)’ is calculated  as :

<img src="4.png" width="">       image source : Wikipedia

<img src="5.png" width="">

                                          
Similarly,for n-dimensional space, the Euclidean distance is given as :

<img src="6.png" width="">


### Lazy Learners

k-NN algorithms are often termed as Lazy learners. Let’s understand why is that. Most of the algorithms like Bayesian classification, logistic regression, SVM etc., are called Eager learners. These algorithms generalize over the training set before receiving the test data i.e. they create a model based on the training data before receiving the test data and then do the prediction/classification on the test data.
But this is not the case with the k-NN algorithm. It doesn’t create a generalized model for the training set but waits for the test data. Once test data is provided then only it starts generalizing the training data to classify the test data.  So, a lazy learner just stores the training data and waits for the test set. Such algorithms work less while training and more while classifying a given test dataset.




### Pros and Cons of KNN Algorithm

Pros:
*	It can be used for both regression and classification problems.
*	It is very simple and easy to implement.
*	Mathematics behind the algorithm is easy to understand.
*	There is no need to create model or do hyperparameter tuning.
*   KNN doesn't make any assumption for the distribution of the given data.
*   There is not much time cost in training phase.

Cons:
*	Finding the optimum value of ‘k’
*	It takes a lot of time to compute the distance between each test sample and all training samples.
*	Since the model is not saved beforehand in this algorithm (lazy learner), so every time one predicts a test value, it follows the same steps again and again.
*	Since, we need to store the whole training set for every test set, it requires a lot of space.
*	It is not suitable for high dimensional data.
*   Expensive in testing phase




# using the social media data set to analyze the usage

# problem satement
   
      The rapid growth of social media usage has significantly impacted users' mental health, productivity, sleep quality, and daily lifestyle. Excessive use of social media may lead to different levels of addiction, making it important to identify users who are at risk. This project aims to build a K-Nearest Neighbors (KNN) classification model that predicts the Addiction_Level of individuals based on factors such as age, daily usage hours, anxiety score, depression score, sleep quality, productivity loss, and other behavioral and psychological attributes. The model can help identify users with different addiction levels and support early intervention and awareness.

# **objective**
     
     To analyze the social media addiction dataset and understand the relationship between user behavior and addiction levels.
To preprocess the dataset by handling missing values, duplicates, and preparing features for machine learning.
To perform Exploratory Data Analysis (EDA) and visualize important patterns in the dataset.
To split the dataset into training and testing sets for model development.
To build a K-Nearest Neighbors (KNN) Classification model to predict the Addiction_Level.
To evaluate the model using metrics such as Accuracy, Precision, Recall, F1-Score, and Confusion Matrix.
To identify the most influential features associated with social media addiction.
To develop a reliable classification model that can assist researchers, educators, and healthcare professionals in identifying different levels of social media addiction.

In [45]:
# import all required libraries

import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.neighbors import KNeighborsRegressor # For regression task
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report,recall_score
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


In [46]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from imblearn.over_sampling import SMOTE

In [47]:
df=pd.read_csv("knn_dataset.csv")

In [48]:
#check the first five rows
df.head()

,Age,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Notifications_Per_Day,FOMO_Score,Social_Comparison_Score,Validation_Seeking_Score,Scroll_Without_Purpose,Anxiety_Score,...,Primary_Platform_Instagram,Primary_Platform_Snapchat,Primary_Platform_TikTok,Primary_Platform_Twitter/X,Primary_Platform_YouTube,Late_Night_Usage_Yes,First_Check_Morning_After 30 min,First_Check_Morning_Within 5 min,Tried_To_Cut_Back_Yes,Failed_To_Cut_Back_Yes
0,30.0,2.9,4.0,3.0,62.0,4.9,7.4,2.1,10.0,2.5,...,False,False,False,False,True,False,False,True,False,False
1,19.0,4.8,1.0,0.0,111.0,4.2,5.4,7.2,9.0,4.0,...,True,False,False,False,False,True,False,True,True,True
2,40.0,4.4,4.0,5.0,122.0,2.7,5.5,5.9,6.1,7.6,...,False,False,False,False,True,False,False,True,False,True
3,37.0,7.7,2.0,3.0,48.0,3.9,8.3,4.9,4.1,3.3,...,False,False,False,False,False,True,False,True,True,False
4,18.0,4.6,3.0,0.0,58.0,6.0,8.6,2.8,7.3,6.5,...,False,False,True,False,False,False,False,False,True,False


In [49]:
#check the last five rows
df.tail()

,Age,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Notifications_Per_Day,FOMO_Score,Social_Comparison_Score,Validation_Seeking_Score,Scroll_Without_Purpose,Anxiety_Score,...,Primary_Platform_Instagram,Primary_Platform_Snapchat,Primary_Platform_TikTok,Primary_Platform_Twitter/X,Primary_Platform_YouTube,Late_Night_Usage_Yes,First_Check_Morning_After 30 min,First_Check_Morning_Within 5 min,Tried_To_Cut_Back_Yes,Failed_To_Cut_Back_Yes
1495,40.0,2.7,2.0,4.0,61.0,8.8,8.6,3.7,6.7,6.2,...,False,False,True,False,False,False,False,False,False,False
1496,23.0,3.5,3.0,6.0,75.0,3.3,6.5,2.9,5.9,2.7,...,False,False,False,False,True,True,False,True,True,False
1497,39.0,5.3,2.0,3.0,87.0,3.2,7.7,9.6,7.1,8.4,...,True,False,False,False,False,True,False,False,True,True
1498,26.0,7.3,4.0,0.0,90.0,3.0,7.3,3.1,1.2,5.8,...,False,False,False,True,False,True,False,True,True,True
1499,16.0,0.7,3.0,2.0,68.0,8.4,6.9,8.3,5.4,2.8,...,False,False,True,False,False,False,False,True,False,False


In [50]:
#check the null values
df.isnull().sum()

,0
Age,0
Daily_Usage_Hours,0
Platforms_Used_Count,0
Posts_Per_Week,0
Notifications_Per_Day,0
FOMO_Score,0
Social_Comparison_Score,0
Validation_Seeking_Score,0
Scroll_Without_Purpose,0
Anxiety_Score,0


In [51]:
#check the duplicated values
df.duplicated().sum()

np.int64(0)

## Domain Analysis
Domain: Healthcare and Social Media Analytics

This project belongs to the Healthcare Analytics and Social Media Analytics domains. It uses machine learning to analyze users' social media behavior and predict their addiction level based on behavioral, psychological, and lifestyle factors. The increasing use of social media platforms has led to concerns about excessive screen time, mental health issues, reduced productivity, poor sleep quality, and emotional well-being. By analyzing these factors, organizations and researchers can identify users at risk and promote healthier digital habits.

The dataset includes attributes such as age, gender, daily usage hours, sleep quality, anxiety score, depression score, self-esteem, academic/work performance, productivity loss, relationship status, and other behavioral indicators. These features help the machine learning model learn patterns associated with different addiction levels (Low, Moderate, High, and Severe).

The K-Nearest Neighbors (KNN) classification algorithm is applied to classify users into the appropriate addiction level based on the similarity of their characteristics. The model can assist healthcare professionals, educational institutions, counselors, researchers, and policymakers in identifying individuals who may require awareness programs, counseling, or early intervention.

# EXPLORATORY DATA ANALYSIS

In [52]:
#check the statistical info
df.describe()

,Age,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Notifications_Per_Day,FOMO_Score,Social_Comparison_Score,Validation_Seeking_Score,Scroll_Without_Purpose,Anxiety_Score,Depression_Score,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,29.372000,4.516867,3.236000,3.936000,60.244667,5.447867,5.495667,5.012600,5.449867,5.110200,4.560333,4.485000,5.523533,5.508267,6.559333,5.025667,5.478933,3.015933,3.024867,6.429733
std,8.550459,2.068691,1.682714,1.948273,33.150688,2.143498,2.006883,2.071148,2.083848,2.122762,2.158510,1.960635,1.946794,1.952002,1.351327,2.077781,1.997259,1.686522,1.657164,1.299288
min,15.000000,0.500000,1.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.500000
25%,22.000000,3.100000,2.000000,3.000000,36.000000,4.100000,4.200000,3.600000,4.000000,3.700000,3.100000,3.200000,4.300000,4.175000,5.700000,3.700000,4.175000,1.800000,1.900000,5.500000
50%,29.000000,4.400000,3.000000,4.000000,59.000000,5.500000,5.500000,5.000000,5.500000,5.100000,4.500000,4.500000,5.600000,5.500000,6.600000,5.000000,5.400000,3.000000,3.000000,6.400000
75%,37.000000,5.800000,4.000000,5.000000,81.250000,6.900000,6.800000,6.400000,6.900000,6.600000,5.900000,5.800000,6.800000,6.800000,7.500000,6.400000,6.900000,4.100000,4.100000,7.300000
max,44.000000,12.000000,8.000000,12.000000,165.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.900000,10.300000,10.000000


In [53]:
# see info about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 38 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Age                               1500 non-null   float64
 1   Daily_Usage_Hours                 1500 non-null   float64
 2   Platforms_Used_Count              1500 non-null   float64
 3   Posts_Per_Week                    1500 non-null   float64
 4   Notifications_Per_Day             1500 non-null   float64
 5   FOMO_Score                        1500 non-null   float64
 6   Social_Comparison_Score           1500 non-null   float64
 7   Validation_Seeking_Score          1500 non-null   float64
 8   Scroll_Without_Purpose            1500 non-null   float64
 9   Anxiety_Score                     1500 non-null   float64
 10  Depression_Score                  1500 non-null   float64
 11  Loneliness_Score                  1500 non-null   float64
 12  Self_E

In [54]:
# lets see distribution of data
plt.figure(figsize=(90,95),facecolor='white')
plotnumber=1
for column in df:
  if plotnumber<=37:
    ax=plt.subplot(7,3,plotnumber)
    sns.distplot(df[column])
    plt.xlabel(column,fontsize=20)
  plotnumber+=1
plt.show()
import warnings
warnings.filterwarnings('ignore')


ValueError: could not convert string to float: 'Low'

In [55]:
df

,Age,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Notifications_Per_Day,FOMO_Score,Social_Comparison_Score,Validation_Seeking_Score,Scroll_Without_Purpose,Anxiety_Score,...,Primary_Platform_Instagram,Primary_Platform_Snapchat,Primary_Platform_TikTok,Primary_Platform_Twitter/X,Primary_Platform_YouTube,Late_Night_Usage_Yes,First_Check_Morning_After 30 min,First_Check_Morning_Within 5 min,Tried_To_Cut_Back_Yes,Failed_To_Cut_Back_Yes
0,30.0,2.9,4.0,3.0,62.0,4.9,7.4,2.1,10.0,2.5,...,False,False,False,False,True,False,False,True,False,False
1,19.0,4.8,1.0,0.0,111.0,4.2,5.4,7.2,9.0,4.0,...,True,False,False,False,False,True,False,True,True,True
2,40.0,4.4,4.0,5.0,122.0,2.7,5.5,5.9,6.1,7.6,...,False,False,False,False,True,False,False,True,False,True
3,37.0,7.7,2.0,3.0,48.0,3.9,8.3,4.9,4.1,3.3,...,False,False,False,False,False,True,False,True,True,False
4,18.0,4.6,3.0,0.0,58.0,6.0,8.6,2.8,7.3,6.5,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,40.0,2.7,2.0,4.0,61.0,8.8,8.6,3.7,6.7,6.2,...,False,False,True,False,False,False,False,False,False,False
1496,23.0,3.5,3.0,6.0,75.0,3.3,6.5,2.9,5.9,2.7,...,False,False,False,False,True,True,False,True,True,False
1497,39.0,5.3,2.0,3.0,87.0,3.2,7.7,9.6,7.1,8.4,...,True,False,False,False,False,True,False,False,True,True
1498,26.0,7.3,4.0,0.0,90.0,3.0,7.3,3.1,1.2,5.8,...,False,False,False,True,False,True,False,True,True,True


In [56]:
df.isnull().sum()

,0
Age,0
Daily_Usage_Hours,0
Platforms_Used_Count,0
Posts_Per_Week,0
Notifications_Per_Day,0
FOMO_Score,0
Social_Comparison_Score,0
Validation_Seeking_Score,0
Scroll_Without_Purpose,0
Anxiety_Score,0


In [57]:
# handle missing values
print(df.isnull().sum())

# Numeric columns
num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

# Categorical columns
cat_cols = df.select_dtypes(include="object").columns

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

Age                                 0
Daily_Usage_Hours                   0
Platforms_Used_Count                0
Posts_Per_Week                      0
Notifications_Per_Day               0
FOMO_Score                          0
Social_Comparison_Score             0
Validation_Seeking_Score            0
Scroll_Without_Purpose              0
Anxiety_Score                       0
Depression_Score                    0
Loneliness_Score                    0
Self_Esteem_Score                   0
Sleep_Quality_Score                 0
Sleep_Hours                         0
Productivity_Loss_Score             0
Offline_Relationship_Quality        0
Physical_Activity_Hrs_Week          0
Screen_Free_Time_Hrs                0
Mental_Wellbeing_Score              0
Addiction_Level                     0
Gender_Male                         0
Gender_Non-binary                   0
Occupation_Student                  0
Occupation_Unemployed               0
Occupation_Working Professional     0
Relationship

In [58]:
# value counts
for col in df.columns:
    print(f"\nValue Counts for {col}:")
    print(df[col].value_counts())


Value Counts for Age:
Age
31.0    64
37.0    61
22.0    61
29.0    60
15.0    56
26.0    56
36.0    55
19.0    52
17.0    52
32.0    52
28.0    51
23.0    50
43.0    50
38.0    50
25.0    50
24.0    50
27.0    49
30.0    49
40.0    48
35.0    48
18.0    48
41.0    48
39.0    46
42.0    45
20.0    44
44.0    44
21.0    43
16.0    42
33.0    39
34.0    37
Name: count, dtype: int64

Value Counts for Daily_Usage_Hours:
Daily_Usage_Hours
4.4     86
0.5     49
3.7     33
3.6     32
4.0     31
        ..
10.1     1
10.6     1
12.0     1
9.1      1
11.0     1
Name: count, Length: 100, dtype: int64

Value Counts for Platforms_Used_Count:
Platforms_Used_Count
3.0    345
2.0    311
4.0    275
1.0    249
5.0    165
6.0     82
7.0     53
8.0     20
Name: count, dtype: int64

Value Counts for Posts_Per_Week:
Posts_Per_Week
3.0     316
4.0     298
2.0     224
5.0     219
6.0     160
1.0     104
7.0      82
8.0      47
0.0      29
10.0      9
9.0       8
11.0      3
12.0      1
Name: count, dtype: in

In [59]:
#replace zero values median
for col in num_cols:

    if col != "Addiction_Level":

        df[col] = df[col].replace(0, df[col].median())

print("Zero values replaced with Median")

Zero values replaced with Median


In [60]:
# label encode all categorical columns
label_encoder = LabelEncoder()

for col in df.select_dtypes(include="object").columns:
    df[col] = label_encoder.fit_transform(df[col])

print(df.head())

    Age  Daily_Usage_Hours  Platforms_Used_Count  Posts_Per_Week  \
0  30.0                2.9                   4.0             3.0   
1  19.0                4.8                   1.0             4.0   
2  40.0                4.4                   4.0             5.0   
3  37.0                7.7                   2.0             3.0   
4  18.0                4.6                   3.0             4.0   

   Notifications_Per_Day  FOMO_Score  Social_Comparison_Score  \
0                   62.0         4.9                      7.4   
1                  111.0         4.2                      5.4   
2                  122.0         2.7                      5.5   
3                   48.0         3.9                      8.3   
4                   58.0         6.0                      8.6   

   Validation_Seeking_Score  Scroll_Without_Purpose  Anxiety_Score  ...  \
0                       2.1                    10.0            2.5  ...   
1                       7.2                     9.

In [61]:
for col in df.columns:
    print(f"\nValue Counts for {col}:")
    print(df[col].value_counts())


Value Counts for Age:
Age
31.0    64
37.0    61
22.0    61
29.0    60
15.0    56
26.0    56
36.0    55
19.0    52
17.0    52
32.0    52
28.0    51
23.0    50
43.0    50
38.0    50
25.0    50
24.0    50
27.0    49
30.0    49
40.0    48
35.0    48
18.0    48
41.0    48
39.0    46
42.0    45
20.0    44
44.0    44
21.0    43
16.0    42
33.0    39
34.0    37
Name: count, dtype: int64

Value Counts for Daily_Usage_Hours:
Daily_Usage_Hours
4.4     86
0.5     49
3.7     33
3.6     32
4.0     31
        ..
10.1     1
10.6     1
12.0     1
9.1      1
11.0     1
Name: count, Length: 100, dtype: int64

Value Counts for Platforms_Used_Count:
Platforms_Used_Count
3.0    345
2.0    311
4.0    275
1.0    249
5.0    165
6.0     82
7.0     53
8.0     20
Name: count, dtype: int64

Value Counts for Posts_Per_Week:
Posts_Per_Week
4.0     327
3.0     316
2.0     224
5.0     219
6.0     160
1.0     104
7.0      82
8.0      47
10.0      9
9.0       8
11.0      3
12.0      1
Name: count, dtype: int64

Value C

In [62]:
#separate feature and target
X = df.drop("Addiction_Level", axis=1)

y = df["Addiction_Level"]

In [63]:
#train and test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


In [64]:
# balance dataset using smote
smote = SMOTE(random_state=42)

X_train, y_train = smote.fit_resample(X_train, y_train)

print(y_train.value_counts())

Addiction_Level
0    360
3    360
2    360
1    360
Name: count, dtype: int64


In [65]:
#feature scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [66]:
#create knn model
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [67]:
#prediction
y_pred = knn.predict(X_test)

In [68]:
#accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

Accuracy : 0.43


In [69]:
#confusion matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[29  5 22 16]
 [16 50 17  1]
 [33 24 25  8]
 [22  0  7 25]]


In [70]:
# clasification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.29      0.40      0.34        72
           1       0.63      0.60      0.61        84
           2       0.35      0.28      0.31        90
           3       0.50      0.46      0.48        54

    accuracy                           0.43       300
   macro avg       0.44      0.43      0.44       300
weighted avg       0.44      0.43      0.43       300



In [71]:
# complete evaluation
print("Accuracy :", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix\n")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report\n")
print(classification_report(y_test, y_pred))

Accuracy : 0.43

Confusion Matrix

[[29  5 22 16]
 [16 50 17  1]
 [33 24 25  8]
 [22  0  7 25]]

Classification Report

              precision    recall  f1-score   support

           0       0.29      0.40      0.34        72
           1       0.63      0.60      0.61        84
           2       0.35      0.28      0.31        90
           3       0.50      0.46      0.48        54

    accuracy                           0.43       300
   macro avg       0.44      0.43      0.44       300
weighted avg       0.44      0.43      0.43       300



# **conclusion**
     
      This project successfully developed a K-Nearest Neighbors (KNN) classification model to predict the Addiction Level of social media users based on their behavioral and psychological characteristics. The dataset was preprocessed by handling missing values, removing duplicate records, replacing zero values with the median, encoding categorical variables using Label Encoding, balancing the training data with SMOTE, and scaling the features using StandardScaler. These preprocessing steps improved the quality of the dataset and enhanced the model's performance.

The trained KNN model was evaluated using Accuracy, Confusion Matrix, Precision, Recall, and F1-Score, demonstrating its ability to classify users into different addiction levels such as Low, Moderate, High, and Severe. The project highlights how machine learning can be effectively applied to analyze social media usage patterns and identify individuals at risk of excessive social media addiction.

Overall, this system provides a reliable and data-driven approach for predicting social media addiction levels. It can support healthcare professionals, educational institutions, researchers, and policymakers in promoting digital well-being, enabling early intervention, and creating awareness about responsible social media usage. Future improvements may include testing advanced machine learning and deep learning algorithms to achieve even higher prediction accuracy and robustness.